import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="w-full text-center py-4 bg-gray-300">
          <p className="text-sm text-gray-900">
            <span className="text-blue-600">©</span> {new Date().getFullYear()}{' '}
            আনা-গন্ডা ক্যালকুলেটর.{' '}
            <span className="italic">All rights reserved by </span>
            <span className="text-amber-900 font-semibold">
              {' '}
              Md. Jobayer Akanda <span className="text-blue-500">& </span>
              Md.Mozameml Hoq
            </span>
          </p>
        </footer>
      </body>
    </html>
  );
}
